name: Deploy Spring Boot to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Deploy to Droplet via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        port: 22
        script: |
          cd ${{ secrets.REPO_DIR }}
          git pull origin main
          pkill -f 'java -jar' || true
          source ~/.bashrc
          ./mvnw clean package -DskipTests
          nohup java -jar target/pathigai-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod > app.log 2>&1 &
